dock-handler: Fix to not walk into errexit just because mounting the fileserver failed

diff --git a/dock-handler b/dock-handler
--- a/dock-handler
+++ b/dock-handler
@@ -66,7 +66,9 @@ case "$DOCKED" in
 		echo 0 > /sys/devices/system/cpu/cpufreq/boost
 
 		# FIXME: Add something like this to unmount your fileserver (in an unclean fashion as the network is already disconnected)
-		# /root/.bin/shell-tools-root/force-unmount-server.sh
+		# if ! /root/.bin/shell-tools-root/force-unmount-server.sh ; then
+		#	echo "WARNING: Unmounting server failed!" >&2
+		# fi
 
 		echo "$(date --rfc-3339=seconds): Undock handler finished."
 	;;
@@ -94,7 +96,9 @@ case "$DOCKED" in
 		echo 1 > /sys/devices/system/cpu/cpufreq/boost
 
 		# FIXME: Add something like this to mount your fileserver
-		# /root/.bin/shell-tools-root/mount-server.sh
+		# if ! /root/.bin/shell-tools-root/mount-server.sh ; then
+		#	echo "WARNING: Mounting server failed!" >&2
+		# fi
 
 		echo "$(date --rfc-3339=seconds): Dock handler finished."
 	;;
